#!/usr/bin/env python3
"""
Chart Generator for Log Activity Analysis

This script reads the CSV files generated by analyze_logs.py and creates
visualizations of the activity data.
"""

import csv
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from pathlib import Path
import numpy as np


def read_monthly_csv(csv_path):
    """Read the monthly activity CSV file."""
    data = {
        'year_month': [],
        'classify': [],
        'map': [],
        'mask': [],
        'subsetter': [],
        'total': []
    }

    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row['Year-Month'] == 'TOTAL':
                break
            data['year_month'].append(row['Year-Month'])
            data['classify'].append(int(row['Classify']))
            data['map'].append(int(row['Map']))
            data['mask'].append(int(row['Mask']))
            data['subsetter'].append(int(row['Subsetter']))
            data['total'].append(int(row['Total']))

    return data


def read_yearly_csv(csv_path):
    """Read the yearly activity CSV file."""
    data = {
        'year': [],
        'classify': [],
        'map': [],
        'mask': [],
        'subsetter': [],
        'total': []
    }

    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row['Year'] == 'TOTAL':
                break
            data['year'].append(row['Year'])
            data['classify'].append(int(row['Classify']))
            data['map'].append(int(row['Map']))
            data['mask'].append(int(row['Mask']))
            data['subsetter'].append(int(row['Subsetter']))
            data['total'].append(int(row['Total']))

    return data


def create_monthly_stacked_bar_chart(data, output_path):
    """Create a stacked bar chart showing monthly activities."""
    fig, ax = plt.subplots(figsize=(14, 8))

    x = np.arange(len(data['year_month']))
    width = 0.6

    # Create stacked bars
    p1 = ax.bar(x, data['classify'], width, label='Classify', color='#2E86AB')
    p2 = ax.bar(x, data['map'], width, bottom=data['classify'],
                label='Map', color='#A23B72')
    p3 = ax.bar(x, data['mask'], width,
                bottom=np.array(data['classify']) + np.array(data['map']),
                label='Mask', color='#F18F01')
    p4 = ax.bar(x, data['subsetter'], width,
                bottom=np.array(data['classify']) + np.array(data['map']) + np.array(data['mask']),
                label='Subsetter', color='#C73E1D')

    ax.set_xlabel('Month', fontsize=12, fontweight='bold')
    ax.set_ylabel('Number of Activities', fontsize=12, fontweight='bold')
    ax.set_title('Monthly Log Activity Summary (Stacked)', fontsize=14, fontweight='bold')
    ax.set_xticks(x)
    ax.set_xticklabels(data['year_month'], rotation=45, ha='right')
    ax.legend(loc='upper left')
    ax.grid(axis='y', alpha=0.3, linestyle='--')

    # Add value labels on bars
    for i in x:
        total = data['total'][i]
        if total > 0:
            ax.text(i, total + 1, str(total), ha='center', va='bottom', fontweight='bold')

    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"Chart saved: {output_path}")
    plt.close()


def create_monthly_grouped_bar_chart(data, output_path):
    """Create a grouped bar chart showing monthly activities."""
    fig, ax = plt.subplots(figsize=(14, 8))

    x = np.arange(len(data['year_month']))
    width = 0.2

    # Create grouped bars
    ax.bar(x - 1.5*width, data['classify'], width, label='Classify', color='#2E86AB')
    ax.bar(x - 0.5*width, data['map'], width, label='Map', color='#A23B72')
    ax.bar(x + 0.5*width, data['mask'], width, label='Mask', color='#F18F01')
    ax.bar(x + 1.5*width, data['subsetter'], width, label='Subsetter', color='#C73E1D')

    ax.set_xlabel('Month', fontsize=12, fontweight='bold')
    ax.set_ylabel('Number of Activities', fontsize=12, fontweight='bold')
    ax.set_title('Monthly Log Activity Summary (Grouped)', fontsize=14, fontweight='bold')
    ax.set_xticks(x)
    ax.set_xticklabels(data['year_month'], rotation=45, ha='right')
    ax.legend(loc='upper left')
    ax.grid(axis='y', alpha=0.3, linestyle='--')

    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"Chart saved: {output_path}")
    plt.close()


def create_monthly_line_chart(data, output_path):
    """Create a line chart showing total monthly activity trend."""
    fig, ax = plt.subplots(figsize=(14, 8))

    x = np.arange(len(data['year_month']))

    # Plot lines for each activity type
    ax.plot(x, data['classify'], marker='o', linewidth=2, label='Classify', color='#2E86AB')
    ax.plot(x, data['map'], marker='s', linewidth=2, label='Map', color='#A23B72')
    ax.plot(x, data['mask'], marker='^', linewidth=2, label='Mask', color='#F18F01')
    ax.plot(x, data['subsetter'], marker='D', linewidth=2, label='Subsetter', color='#C73E1D')
    ax.plot(x, data['total'], marker='*', linewidth=3, markersize=12,
            label='Total', color='#000000', linestyle='--')

    ax.set_xlabel('Month', fontsize=12, fontweight='bold')
    ax.set_ylabel('Number of Activities', fontsize=12, fontweight='bold')
    ax.set_title('Monthly Log Activity Trends', fontsize=14, fontweight='bold')
    ax.set_xticks(x)
    ax.set_xticklabels(data['year_month'], rotation=45, ha='right')
    ax.legend(loc='upper left')
    ax.grid(True, alpha=0.3, linestyle='--')

    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"Chart saved: {output_path}")
    plt.close()


def create_yearly_comparison_chart(data, output_path):
    """Create a grouped bar chart comparing yearly activities."""
    fig, ax = plt.subplots(figsize=(10, 8))

    x = np.arange(len(data['year']))
    width = 0.15

    # Create grouped bars
    ax.bar(x - 2*width, data['classify'], width, label='Classify', color='#2E86AB')
    ax.bar(x - width, data['map'], width, label='Map', color='#A23B72')
    ax.bar(x, data['mask'], width, label='Mask', color='#F18F01')
    ax.bar(x + width, data['subsetter'], width, label='Subsetter', color='#C73E1D')
    ax.bar(x + 2*width, data['total'], width, label='Total', color='#000000', alpha=0.6)

    ax.set_xlabel('Year', fontsize=12, fontweight='bold')
    ax.set_ylabel('Number of Activities', fontsize=12, fontweight='bold')
    ax.set_title('Yearly Log Activity Comparison', fontsize=14, fontweight='bold')
    ax.set_xticks(x)
    ax.set_xticklabels(data['year'])
    ax.legend(loc='upper left')
    ax.grid(axis='y', alpha=0.3, linestyle='--')

    # Add value labels on bars
    for i in x:
        total = data['total'][i]
        ax.text(i + 2*width, total + 1, str(total), ha='center', va='bottom', fontweight='bold')

    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"Chart saved: {output_path}")
    plt.close()


def create_activity_type_pie_chart(monthly_data, output_path):
    """Create a pie chart showing distribution of activity types."""
    fig, ax = plt.subplots(figsize=(10, 8))

    # Calculate totals for each activity type
    totals = {
        'Classify': sum(monthly_data['classify']),
        'Map': sum(monthly_data['map']),
        'Mask': sum(monthly_data['mask']),
        'Subsetter': sum(monthly_data['subsetter'])
    }

    labels = list(totals.keys())
    sizes = list(totals.values())
    colors = ['#2E86AB', '#A23B72', '#F18F01', '#C73E1D']
    explode = (0.05, 0.05, 0.05, 0.05)

    wedges, texts, autotexts = ax.pie(sizes, explode=explode, labels=labels, colors=colors,
                                        autopct='%1.1f%%', shadow=True, startangle=90)

    # Enhance text
    for text in texts:
        text.set_fontsize(12)
        text.set_fontweight('bold')

    for autotext in autotexts:
        autotext.set_color('white')
        autotext.set_fontsize(10)
        autotext.set_fontweight('bold')

    ax.set_title('Distribution of Activity Types (All Time)', fontsize=14, fontweight='bold')

    # Add legend with counts
    legend_labels = [f'{label}: {size}' for label, size in zip(labels, sizes)]
    ax.legend(legend_labels, loc='center left', bbox_to_anchor=(1, 0, 0.5, 1))

    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"Chart saved: {output_path}")
    plt.close()


def create_dashboard(monthly_data, yearly_data, output_path):
    """Create a dashboard with multiple charts."""
    fig = plt.figure(figsize=(16, 10))
    gs = fig.add_gridspec(2, 2, hspace=0.3, wspace=0.3)

    # Chart 1: Monthly stacked bar
    ax1 = fig.add_subplot(gs[0, :])
    x = np.arange(len(monthly_data['year_month']))
    width = 0.6

    p1 = ax1.bar(x, monthly_data['classify'], width, label='Classify', color='#2E86AB')
    p2 = ax1.bar(x, monthly_data['map'], width, bottom=monthly_data['classify'],
                label='Map', color='#A23B72')
    p3 = ax1.bar(x, monthly_data['mask'], width,
                bottom=np.array(monthly_data['classify']) + np.array(monthly_data['map']),
                label='Mask', color='#F18F01')
    p4 = ax1.bar(x, monthly_data['subsetter'], width,
                bottom=np.array(monthly_data['classify']) + np.array(monthly_data['map']) + np.array(monthly_data['mask']),
                label='Subsetter', color='#C73E1D')

    ax1.set_xlabel('Month', fontsize=10, fontweight='bold')
    ax1.set_ylabel('Activities', fontsize=10, fontweight='bold')
    ax1.set_title('Monthly Activity Summary', fontsize=12, fontweight='bold')
    ax1.set_xticks(x)
    ax1.set_xticklabels(monthly_data['year_month'], rotation=45, ha='right', fontsize=9)
    ax1.legend(loc='upper left')
    ax1.grid(axis='y', alpha=0.3, linestyle='--')

    # Chart 2: Activity type pie chart
    ax2 = fig.add_subplot(gs[1, 0])
    totals = {
        'Classify': sum(monthly_data['classify']),
        'Map': sum(monthly_data['map']),
        'Mask': sum(monthly_data['mask']),
        'Subsetter': sum(monthly_data['subsetter'])
    }
    labels = list(totals.keys())
    sizes = list(totals.values())
    colors = ['#2E86AB', '#A23B72', '#F18F01', '#C73E1D']

    wedges, texts, autotexts = ax2.pie(sizes, labels=labels, colors=colors,
                                        autopct='%1.1f%%', startangle=90)
    for autotext in autotexts:
        autotext.set_color('white')
        autotext.set_fontsize(9)
        autotext.set_fontweight('bold')
    ax2.set_title('Activity Distribution', fontsize=12, fontweight='bold')

    # Chart 3: Yearly comparison
    ax3 = fig.add_subplot(gs[1, 1])
    x_yearly = np.arange(len(yearly_data['year']))
    width_yearly = 0.15

    ax3.bar(x_yearly - 2*width_yearly, yearly_data['classify'], width_yearly, label='Classify', color='#2E86AB')
    ax3.bar(x_yearly - width_yearly, yearly_data['map'], width_yearly, label='Map', color='#A23B72')
    ax3.bar(x_yearly, yearly_data['mask'], width_yearly, label='Mask', color='#F18F01')
    ax3.bar(x_yearly + width_yearly, yearly_data['subsetter'], width_yearly, label='Subsetter', color='#C73E1D')

    ax3.set_xlabel('Year', fontsize=10, fontweight='bold')
    ax3.set_ylabel('Activities', fontsize=10, fontweight='bold')
    ax3.set_title('Yearly Comparison', fontsize=12, fontweight='bold')
    ax3.set_xticks(x_yearly)
    ax3.set_xticklabels(yearly_data['year'])
    ax3.legend(loc='upper left', fontsize=9)
    ax3.grid(axis='y', alpha=0.3, linestyle='--')

    fig.suptitle('Log Activity Analysis Dashboard', fontsize=16, fontweight='bold', y=0.98)

    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"Dashboard saved: {output_path}")
    plt.close()


def main():
    """Main entry point."""
    print("Creating charts from CSV data...")
    print()

    # Get the directory where the script is located
    script_dir = Path(__file__).parent

    # Read CSV files
    monthly_csv = script_dir / 'log_activity_monthly.csv'
    yearly_csv = script_dir / 'log_activity_yearly.csv'

    if not monthly_csv.exists() or not yearly_csv.exists():
        print("Error: CSV files not found. Please run analyze_logs.py first.")
        return

    monthly_data = read_monthly_csv(monthly_csv)
    yearly_data = read_yearly_csv(yearly_csv)

    # Create output directory for charts
    charts_dir = script_dir / 'charts'
    charts_dir.mkdir(exist_ok=True)

    # Generate charts
    create_monthly_stacked_bar_chart(monthly_data, charts_dir / 'monthly_stacked_bar.png')
    create_monthly_grouped_bar_chart(monthly_data, charts_dir / 'monthly_grouped_bar.png')
    create_monthly_line_chart(monthly_data, charts_dir / 'monthly_line_chart.png')
    create_yearly_comparison_chart(yearly_data, charts_dir / 'yearly_comparison.png')
    create_activity_type_pie_chart(monthly_data, charts_dir / 'activity_distribution_pie.png')
    create_dashboard(monthly_data, yearly_data, charts_dir / 'dashboard.png')

    print()
    print(f"All charts have been saved to: {charts_dir}")
    print("Charts created:")
    print("  - monthly_stacked_bar.png")
    print("  - monthly_grouped_bar.png")
    print("  - monthly_line_chart.png")
    print("  - yearly_comparison.png")
    print("  - activity_distribution_pie.png")
    print("  - dashboard.png")


if __name__ == '__main__':
    main()
